### ISSUE TITLE
About "Sudden Convergence" phenomenon

### ISSUE THREAD

**Issue by PreFKim** [fluide1022/MCM#1]
Thank you for your contribution to motion synthesis. 

I'm interested in your research paper. 

From my understanding, the MCM structure is inspired by ControlNet. 

In ControlNet, there was a phenomenon known as 'sudden convergence' experienced during the training of the ControlNet model. 

Did you experience the same phenomenon?

**Comment by ZeyuLing** [comment]
Thank you for your attention! We didn't experience this phenomenon during training. Maybe it's because of the structure and task difference between MCM and Control-Net

**Comment by ZeyuLing** [comment]
> Thank you for your contribution to motion synthesis.
> 
> I'm interested in your research paper.
> 
> From my understanding, the MCM structure is inspired by ControlNet.
> 
> In ControlNet, there was a phenomenon known as 'sudden convergence' experienced during the training of the ControlNet model.
> 
> Did you experience the same phenomenon?

Thank you for your attention! We didn't experience this phenomenon during training. Maybe it's because of the structure and task difference between MCM and Control-Net

**Comment by PreFKim** [comment]
Thank you for your answer.

In your paper, in Table 3, you captioned it as 'Table 3: The results on the HumanML3D dataset after training Transformer Decoder modules with different structures for 500 epochs.'

Were all other experiments(Table 1, Table 2 etc.) conducted for the same number of epochs?

**Comment by ZeyuLing** [comment]
No, only results in Table 3 were only trained for 500 epochs(it takes too much time to train entirely).  We trained MCM for 2000 epochs for Table 2 and another 2000 epochs(4000 in total) for Table 1.

**Comment by PreFKim** [comment]
Thank you for your reply, and contribution to motion synthesis.
