### ISSUE TITLE
About MWNet Architecture

### ISSUE THREAD

**Issue by feifeitu1** [fluide1022/MCM#3]
This work is highly innovative. I am very curious about your work.But I have some problems about MWnet.

I want to know how the channel-wise self-attention part is specifically designed, as HumanML3d is not directly a combination of joint features. I am interested in how the joint features are divided to calculate the attention. Is there a more detailed appendix I can refer to? And when will you open your code?

Thank you very much!!!

**Comment by ZeyuLing** [comment]
Sorry for my late reply! HumanML3D contains joint position, rotation, velocity and feet contcact information, we simply divide the latent features into several groups and conduct self-attention in every group.  In our implementation, the 263-dim hm3d vector is firstly projected into 512-dim latent feature. Then the 512-dim feature is divided into 8 groups(64 channels for each group).  
Sorry for being too busy lately and haven't had time to organize the code. I'll release it as soon as possible!

**Comment by feifeitu1** [comment]
Thanks for your reply！
